{
    name: 'whole milk',
    image: '/images/whole_milk.jpg',
    description:
      'Tastes Yummy',
      brand: 'Amul',
      category: 'diary',
    price: 30,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'condensed milk',
    image: '/images/condensed_milk.jpg',
    description:
      'Tastes Yummy',
      brand: 'Amul',
      category: 'diary',
    price: 40,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'whipped cream',
    image: '/images/whipped_cream.jpg',
    description:
      'Tastes Yummy',
      brand: 'Arun',
      category: 'cooking and baking needs',
    price: 120,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'sugar',
    image: '/images/sugar.jpg',
    description:
      'Extreme Sweetness',
      brand: 'BB Popular',
      category: 'salt sugar and jaggery',
    price: 25,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'sour cream',
    image: '/images/sour_cream.jpg',
    description:
      'Burst of flavour',
      brand: 'pringles',
      category: 'snacks and namkeen',
    price: 30,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'soda',
    image: '/images/soda.jpg',
    description:
      'Carbonated Water, Salts of Magnesium and Sodium',
      brand: 'Kinley',
      category: 'Bevarages',
    price: 20,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},
{
    name: 'pork',
    image: '/images/pork.jpg',
    description:
      'Fresh and soft',
      brand: 'sneha pork',
      category: 'Meat',
    price: 400,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'napkins',
    image: '/images/napkins.jpeg',
    description:
      'soft and easily degreadable',
      brand: 'BB Home',
      category: 'Disposables',
    price: 60,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'margarine',
    image: '/images/margarine.jpg',
    description:
      'Tastes Yummy',
      brand: 'Amul',
      category: 'Diary',
    price: 60,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'hamburger meat',
    image: '/images/hamburger.jpg',
    description:
      'soft and fresh',
      brand: 'sneha meat',
      category: 'Meat',
    price: 400,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'ham',
    image: '/images/ham.jpg',
    description:
      'fresh and soft',
      brand: 'sneha ham',
      category: 'Meat',
    price: 150,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'Frank Furter',
    image: '/images/frank_furter.jpg',
    description:
      'Tastes Yummy',
      brand: 'BB Home',
      category: 'Diary',
    price: 45,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'Dessert',
    image: '/images/desert.jpg',
    description:
      'soft and juicy',
      brand: 'Gits',
      category: 'Sauces',
    price: 95,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'pip fruit',
    image: '/images/pip_fruit.jpg',
    description:
      'fresh and healthy and organic',
      brand: 'Fresho',
      category: 'Fruits',
    price: 25,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'citrus fruit',
    image: '/images/citrus_fruit.jpg',
    description:
      'fresh and healthy and organic',
      brand: 'Fresho',
      category: 'Fruits',
    price: 65,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
    name: 'Tropical fruit',
    image: '/images/tropical_fruit.jpg',
    description:
      'fresh and healthy and organic',
      brand: 'Fresho',
      category: 'Fruits',
    price: 200,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
  },
{
name: 'vegetables',
image: '/images/vegetables.jpg',
description:
  'fresh and healthy and organic',
  brand: 'Fresho',
  category: 'vegetables',
price: 23,
countInStock: 100,
rating: 0,
numReviews: 0,
  },
{
    name: 'root vegetables',
    image: '/images/root_vegetables.jpg',
    description:
      'fresh and healthy and organic',
      brand: 'Fresho',
      category: 'vegetables',
    price: 15,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},
{
    name: 'berries',
    image: '/images/berries.jpg',
    description:
      'fresh and healthy and organic',
      brand: 'Fresho',
      category: 'fruits',
    price: 76,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},
{
    name: 'frozen vegetables',
    image: '/images/frozen_vegetables.jpeg',
    description:
      'fresh and healthy and organic',
      brand: 'Fresho',
      category: 'vegetables',
    price: 27,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},

{
    name: 'Beef',
    image: '/images/beef.jpeg',
    description:
      'soft and fresh',
      brand: 'sneha beef',
      category: 'Meat',
    price: 250,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},
{
    name: 'chocolate',
    image: '/images/chocolate.jpg',
    description:
      'Yummy',
      brand: 'Amul',
      category: 'snack',
    price: 100,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},
{
    name: 'Bottled Water',
    image: '/images/bottled_water.jpeg',
    description:
      'clean and purified',
      brand: 'BB Home',
      category: 'refreshment',
    price: 20,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},

{
    name: 'cakes',
    image: '/images/cakes.jpg',
    description:
      'Yummy',
      brand: 'Amul',
      category: 'snack',
    price: 100,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},
{
    name: 'cheese',
    image: '/images/cheese.jpeg',
    description:
      'Yummy',
      brand: 'Amul',
      category: 'snack',
    price: 60,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},
{
    name: 'oil',
    image: '/images/oil.jpeg',
    description:
      'Healthy',
      brand: 'sunflower',
      category: 'Edible oils',
    price: 100,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},
{
    name: 'sausage',
    image: '/images/sausage.jpeg',
    description:
      'Yummy',
      brand: 'Amul',
      category: 'snacks',
    price: 20,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},
{
    name: 'coffee',
    image: '/images/coffee.jpeg',
    description:
      'Gives Relaxing Feeling',
      brand: 'BRU',
      category: 'Diary',
    price: 5,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},
{
    name: 'canned beer',
    image: '/images/canned_beer.jpeg',
    description:
      'Relax',
      brand: 'coolberg',
      category: 'beverages',
    price: 71,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},
{
    name: 'shopping Bag',
    image: '/images/shopping_bag.jpg',
    description:
      'comfortable',
      brand: 'BB Home',
      category: 'Bags',
    price: 8,
    countInStock: 100,
    rating: 0,
    numReviews: 0,
},